### ISSUE TITLE
X-Forwarded-For header requires server to run behind proxy

### ISSUE THREAD

**Issue by robere2** [NoahTheNerd/lavacake#3]
Bun does not set the `X-Forwarded-For` header automatically. Instead, it must be set by an upstream trusted proxy (e.g. an NGINX server). However, there's no mention of this in the README.

It seems like this might be an oversight which hadn't been an issue until PR #2. Before this PR, a blank `X-Forwarded-For` header may have not resulted in an error, but just a broken rate limit. PR #2 changes the rate limit code to resolve some TypeScript errors, but it also throws an error if `X-Forwarded-For` is not set.

What is the intended behavior? Should a reverse proxy like NGINX be required, or should rate limiting be handled in some other way? It seems like Bun [does not currently support any way to natively get the client IP address](https://github.com/oven-sh/bun/issues/3540).

**Comment by NoahTheNerd** [comment]
Sorry, I was originally using this for my personal server which runs Caddy & NGINX. Will look into alternate implementations of ratelimiting.
